allowBuilds:
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@opencode/ai@2.0.18'
  - '@opencode/client@2.0.18'
  - '@opencode/plugin@2.0.18'
  - '@opencode/protocol@2.0.18'
  - '@opencode/schema@2.0.18'
  - '@opencode/util@2.0.18'
